# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- master

jobs:

# Linux tests
- template: azure-test-template.yml
  parameters: {os: linux, python: 2.7, py_name: py27}
- template: azure-test-template.yml
  parameters: {os: linux, python: 3.4, py_name: py34}
- template: azure-test-template.yml
  parameters: {os: linux, python: 3.5, py_name: py35}
- template: azure-test-template.yml
  parameters: {os: linux, python: 3.6, py_name: py36}
- template: azure-test-template.yml
  parameters: {os: linux, python: 3.7, py_name: py37}

# Windows tests
- template: azure-test-template.yml
  parameters: {os: windows, python: 2.7, py_name: py27}
- template: azure-test-template.yml
  parameters: {os: windows, python: 3.4, py_name: py34}
- template: azure-test-template.yml
  parameters: {os: windows, python: 3.5, py_name: py35}
- template: azure-test-template.yml
  parameters: {os: windows, python: 3.6, py_name: py36}
- template: azure-test-template.yml
  parameters: {os: windows, python: 3.7, py_name: py37}

# MacOs tests
- template: azure-test-template.yml
  parameters: {os: macOs, python: 2.7, py_name: py27}
- template: azure-test-template.yml
  parameters: {os: macOs, python: 3.4, py_name: py34}
- template: azure-test-template.yml
  parameters: {os: macOs, python: 3.5, py_name: py35}
- template: azure-test-template.yml
  parameters: {os: macOs, python: 3.6, py_name: py36}
- template: azure-test-template.yml
  parameters: {os: macOs, python: 3.7, py_name: py37}

- job: 'Publish'
  dependsOn:
    - linux_py27_test
    - linux_py34_test
    - linux_py35_test
    - linux_py36_test
    - linux_py37_test
    - windows_py27_test
    - windows_py34_test
    - windows_py35_test
    - windows_py36_test
    - windows_py37_test
    - macOs_py27_test
    - macOs_py34_test
    - macOs_py35_test
    - macOs_py36_test
    - macOs_py37_test
  pool:
    vmImage: 'Ubuntu-16.04'

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.x'
      architecture: 'x64'

  - script: python setup.py sdist
    displayName: 'Build sdist'
